### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by petehjfd** [youandmedigital/craft-breadcrumb#10]
Hi, is there any plan to support Craft 4?

Thanks

**Comment by jonleverrier** [comment]
Hi Pete - the short answer is yes!

**Comment by petehjfd** [comment]
That's great news, thanks.  Any chance you can give an ETA?

**Comment by chadcrowell** [comment]
Hi @jonleverrier do you have a timeline for C4 release?

**Comment by jonleverrier** [comment]
@petehjfd @chadcrowell - So sorry for the radio silence. For what it's worth... I just released version `v2.0.0` that now supports Craft CMS 4.

https://github.com/youandmedigital/craft-breadcrumb/tree/craft-4
