### ISSUE TITLE
Craft5 Support

### ISSUE THREAD

**Issue by JMKelley** [youandmedigital/craft-breadcrumb#11]
Are you guys looking to do Craft5 Support?

**Comment by jonleverrier** [comment]
Hi @JMKelley - the short answer is yes. Hopefully in the coming weeks.

**Comment by jonleverrier** [comment]
@JMKelley You should be all set. I appreciate your patience!

**Comment by jonleverrier** [comment]
Closed via https://github.com/youandmedigital/craft-breadcrumb/commit/2a8780fd289060b56e85e763bd61b2af4d324151

**Comment by JMKelley** [comment]
@jonleverrier Legend. Thanks
