### ISSUE TITLE
Why are my breadcrumb titles returning english in a multilingual site setup ?

### ISSUE THREAD

**Issue by bryantAXS** [youandmedigital/craft-breadcrumb#5]
It doesn't seem like multi-language is supported, is that correct? Do you have any suggestions on how to implement or when that would be implemented?

**Comment by jonleverrier** [comment]
Hi @bryantAXS 

Breadcrumb should be fine in a multi-language setup - what's not working for you?

How have you configured Breadcrumb? Do you have base urls setup for each language in Craft?

**Comment by bryantAXS** [comment]
Hmm here is my breadcrumb config:

```
craft.breadcrumb.config({ homeTitle: 'Home' | t})
```

And here's the Site's config: https://cl.ly/48b5331a7c67

Those variables are set inside the `.env.php` file: https://cl.ly/e892597b4b46

Anything you see I'm doing wrong here?

**Comment by bryantAXS** [comment]
And to be clear, the problem is that the titles returned from the config are still showing the English names, not the Spanish ones: https://cl.ly/e67101036f76

**Comment by jonleverrier** [comment]
Thanks for the info! I'll come back with a solution shortly.

**Comment by jonleverrier** [comment]
@bryantAXS - Just a small point, but the example Breadcrumb configuration you provided won't work. The minimum setup required can be found in the Breadcrumb [readme](https://github.com/youandmedigital/craft-breadcrumb#breadcrumb-overview).

> https://cl.ly/e67101036f76

Also, looking at the screen shot you provided above, I can see you're browsing the Spanish version of the site, but the URLs are in English, not Spanish.

Breadcrumb simply generates a breadcrumb from the page URL. So, if you're on your Spanish site and the URLs are in English, your breadcrumb will be in English too. That's the limitation of the plugin.

Once you have the basics setup, there are options to configure the first and last item in the breadcrumb (if that is even required).

Please let me know how you get on or if I can be of any further assistance.

**Comment by jonleverrier** [comment]
Since v1.1.0, Breadcrumb will now generate crumb titles from the customFieldHandle setting if set, falling back to the title field. If none of these fields are present, it will generate the crumb title from the URL segment.

So it doesn't matter if your uri's are in english on a different language site.
