### ISSUE TITLE
How do I show the entry title in my breadcrumb?

### ISSUE THREAD

**Issue by thefubon** [youandmedigital/craft-breadcrumb#8]
Please tell me how to display the title. Handle is displayed.
![Снимок-экрана-2019-12-05-в-10 51 33](https://user-images.githubusercontent.com/43171309/70215037-a8cab900-174d-11ea-9bcd-1847a8b831d5.jpg)

**Comment by jonleverrier** [comment]
Hi @thefubon 

Can you show me your breadcrumb settings array. For example:

```twig
{# Breadcrumb settings array #}
{% set settings =
    {
        homeTitle: 'My Website',
        customBaseUrl: 'https://example.com/123',
        customFieldHandleEntryId: element.id,
        customFieldHandle: 'myCustomField',
        lastSegmentTitle: element.customMenuTitle ?? element.title,
        skipUrlSegment: 2,
        limit: 3
    }
%}
```

**Comment by jonleverrier** [comment]
Also, could you send me a screen shot of the control panel entry for home/news ?

**Comment by thefubon** [comment]
I saw this in the documentation but I was able to figure out how to specify the parameters correctly
```
{% set breadcrumb = craft.breadcrumb.config %}
  {# Breadcrumb settings array #}
  {% set settings =
      {
          homeTitle: 'My Website',
          customBaseUrl: 'https://example.com/123',
          customFieldHandleEntryId: element.id,
          customFieldHandle: 'breadcrumb',
          lastSegmentTitle: element.customMenuTitle ?? element.title,
          skipUrlSegment: 2,
          limit: 3
      }
  %}
  {% if breadcrumb|length > 1 %}
  <div class="c-breadcrumb uk-section uk-section-xsmall uk-container uk-container-medium">
    <ul class="c-breadcrumb__items uk-breadcrumb">
      {% for crumb in breadcrumb  %}
        {% if loop.last %}
        <li class="c-breadcrumb__item"><span>{{ crumb.title }}</span></li>
        {% else %}
        <li class="c-breadcrumb__item"><a class="c-breadcrumb__link" href="{{ crumb.url }}"><span>{{ crumb.title }}</span></a></li>
        {% endif %}
      {% endfor %}
    </ul>
  </div>
  {% endif %}
```

**Comment by jonleverrier** [comment]
Remember that crumb titles are generated from entry pages. 

>Breadcrumb will generate crumb titles from the customFieldHandle setting if set, falling back to the title field. If none of these fields are present, it will generate the crumb title from the URL segment

If you just want to use the page title, remove `customFieldHandleEntryId` and `customFieldHandle` from the settings array. For example:

```twig
{# Breadcrumb settings array #}
{% set settings =
    {
        homeTitle: 'My Website',
        customBaseUrl: 'https://example.com/123',
        lastSegmentTitle: element.customMenuTitle ?? element.title,
        skipUrlSegment: 2,
        limit: 3
    }
%}
```

**Comment by thefubon** [comment]
Does not work
<img width="758" alt="Снимок экрана 2019-12-05 в 11 41 40" src="https://user-images.githubusercontent.com/43171309/70218749-a4ee6500-1754-11ea-8e6c-a2ed160037ad.png">
<img width="1168" alt="Снимок экрана 2019-12-05 в 11 41 49" src="https://user-images.githubusercontent.com/43171309/70218750-a4ee6500-1754-11ea-8c80-78b9c00cfc9c.png">
<img width="1577" alt="Снимок экрана 2019-12-05 в 11 41 59" src="https://user-images.githubusercontent.com/43171309/70218751-a4ee6500-1754-11ea-9496-b70c00a5fa77.png">

**Comment by thefubon** [comment]
https://monopixel.ru/news/005-новости-3

**Comment by jonleverrier** [comment]
It looks like your breadcrumb title is being generated from the URL. 

This means that:

1. You have no custom field assigned to your entries. You would specify the custom field using the `customFieldHandle` setting.
2. You don't have traditional entry titles

**Comment by thefubon** [comment]
I'm understood, thank you

**Comment by thefubon** [comment]
Only I do not understand how to do this)

**Comment by jonleverrier** [comment]
Try:

1. Create a text field for your `news` `channel` with the handle `breadcrumbTitle`
2. Go to an entry in your `news` `channel` and make sure the field `breadcrumbTitle` appears
3. Populate the field `breadcrumbTitle` with some content and save the entry

Once you have done this, use the following settings example:

```twig
{# If entry is empty, try category, tag and finally return null #}
{% set element = entry ?? category ?? tag ?? null %}

{# Breadcrumb settings array #}
{% set settings =
    {
        customFieldHandleEntryId: element.id,
        customFieldHandle: 'breadcrumbTitle'
    }
%}
```

**Comment by thefubon** [comment]
```
{% extends "_layout" %}
**{% set title = "News" %}**
{% block main %}
```

And how to use this variable?  set title

**Comment by jonleverrier** [comment]
You could try adding `title` to the `customFieldHandle` in the settings array rather than `breadcrumbTitle`.

I'm not quite sure what you're trying to achieve - my examples above should have you covered.
